name: GH CDEvents PoC
on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  sendCDEvent:    
    name: Send CDEvent
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.16.1' # The Go version to download (if necessary) and use.
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        go run gh-cdevents.go
    